apiVersion: v1
kind: Service
metadata:
    name: "chickenkavalacluster-fc62"
    labels:
        app: "chickenkavalacluster-fc62"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "chickenkavalacluster-fc62"