on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jackdaniels.azurecr.io
        username: ${{ secrets.acr_jackdaniels_username }}
        password: ${{ secrets.acr_jackdaniels_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t jackdaniels.azurecr.io/chickenkavalacluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push jackdaniels.azurecr.io/chickenkavalacluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_chickenkavalacluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep chickenkavali | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace chickenkavali`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: chickenkavali
        container-registry-url: jackdaniels.azurecr.io
        container-registry-username: ${{ secrets.acr_jackdaniels_username }}
        container-registry-password: ${{ secrets.acr_jackdaniels_password }}
        secret-name: chickenkavaldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: chickenkavali
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          jackdaniels.azurecr.io/chickenkavalacluster:${{ github.sha }}
        imagepullsecrets: |
          chickenkavaldockerauth
